import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserContext } from './auth/UserContext'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { ModalProvider } from './context/ModalContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext>
          <ModalProvider>
            {children}
          </ModalProvider>
          <ToastContainer />
        </UserContext>
      </body>
    </html>
  )
}
